app {
  name = "autentigo"
  version = "SNAPSHOT"
  host = "0.0.0.0"
  port = ${?APP_PORT}
}

postgres {
  uri = ${?POSTGRES_URL}
  user = ${?POSTGRES_USER}
  password = ${?POSTGRES_PASSWORD}
}

services {
  jwt {
    issuer = ${?JWT_ISSUER}
    private-key-pem = ${?JWT_PRIVATE_KEY_PEM}
    public-key-pem = ${?JWT_PUBLIC_KEY_PEM}
    access-expiration = 24h
    refresh-expiration = 30d
  }

  password-reset {
    expiration = 15m
  }

  smtp {
    host = ${?SMTP_HOST}
    port = ${?SMTP_PORT}
    username = ${?SMTP_USERNAME}
    password = ${?SMTP_PASSWORD}
    from-address = ${?SMTP_FROM_ADDRESS}
  }
}
